### ISSUE TITLE
Getting the Red Screen of Death

### ISSUE THREAD

**Issue by orhanmaden** [d-a-n/react-native-modal-picker#10]
I ran `react 0.14.8` and `react-native 0.25.1`. I also checked with the latest versions: `react 15.0.2` and `react-native 0.26.0`.

I copied and pasted the code of the README.md file of the github repository. And also cloned the rep and build it locally. Got the same result: Red Screen of Death.

I also followed the steps in the Red Screen of Death but also no luck with it.

I would appreciate any suggestions.

![screen shot 2016-05-21 at 23 33 23](https://cloud.githubusercontent.com/assets/3224537/15450980/557fe59e-1fae-11e6-8041-f3eabfd2bd1a.png)

**Comment by caroaguilar** [comment]
The issue is that in line 17 it's importing rebound package and it's not added as a dependency in package.json. The rebound module is not even used so the workaround I found in the meantime is to npm install the module normally and then open node_modules/react-native-modal-picker/index.js and delete the line 17 which says `import rebound from 'rebound';`

**Comment by orhanmaden** [comment]
@caroaguilar Thanks! I also noticed it: Check https://github.com/d-a-n/react-native-modal-picker/issues/11 for more clarity. I will close this issue.
